server:
  port: 8888


spring:
  application:
    name: file-manager
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/file_manager
    username: ${R2DBC_USER}
    password: ${R2DBC_PASSWORD}
  flyway:
    url: jdbc:mysql://localhost:3306/file_manager
    locations: classpath:db/migration
    user: ${FLYWAY_USER}
    password: ${FLYWAY_PASSWORD}
  sql:
    init:
      mode: always

minio:
  endpoint: http://127.0.0.1:9000
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  bucket: my-bucket
  region: us-east-1

jwt:
  password:
    encoder:
      secret: ${JWT_ENCODER_SECRET}
      iterations: 64
      keyLength: 256
  expiration: 3600
  issuer: nikita