server:
  port: 8888

spring:
  application:
    name: file-manager
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/file_manager
    username: ${r2dbc.user}
    password: ${r2dbc.password}
  flyway:
    url: jdbc:mysql://localhost:3306/file_manager
    locations: classpath:db/migration
    user: ${flyway.user}
    password: ${flyway.password}

minio:
  endpoint: http://127.0.0.1:9000
  access-key: ${minio.access-key}
  secret-key: ${minio.secret-key}
  bucket: my-bucket
  region: us-east-1

jwt:
  password:
    encoder:
      secret: ${jwt.password.encoder.secret}
      iterations: 64
      keyLength: 256
  expiration: 3600
  issuer: nikita