server:
  port: 8888

spring:
  application:
    name: file-manager
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/file_manager
    username: root
    password: password
  flyway:
    url: jdbc:mysql://localhost:3306/file_manager
    locations: classpath:db/migration
    user: root
    password: password

minio:
  endpoint: http://127.0.0.1:9000
  access-key: admin
  secret-key: password
  bucket: my-bucket
  region: us-east-1

jwt:
  password:
    encoder:
      secret: dmVyeXZlcnlzdHJvbmdzZWNyZXRwYXNzd29yZCE=
      iterations: 64
      keyLength: 256
  expiration: 3600
  issuer: nikita